### ISSUE TITLE
split_merge sample refers to non-existent split_merge_config.yml

### ISSUE THREAD

**Issue by sethfitz** [aws-samples/aws-flow-ruby-samples#7]
https://github.com/awslabs/aws-flow-ruby-samples/tree/master/samples/split_merge#configure-the-sample

**Comment by mojodna** [comment]
`splitmerge_utils.rb` contains workflow configuration, including the S3 bucket to be used for communicating large payloads.

**Comment by EronHennessey** [comment]
Thanks, I'll fix this up!

**Comment by EronHennessey** [comment]
Fixed in the PR referenced above. Here's the [fixed README](https://github.com/awslabs/aws-flow-ruby-samples/blob/master/samples/split_merge/README.md)
