### ISSUE TITLE
split_merge sample refers to non-existent files

### ISSUE THREAD

**Issue by sethfitz** [aws-samples/aws-flow-ruby-samples#8]
From https://github.com/awslabs/aws-flow-ruby-samples/blob/master/samples/split_merge/README.md:

``` bash
ruby average_calculator_activity.rb
ruby average_calculator_workflow.rb
ruby average_calculator_workflow_starter.rb
```

This works:

``` bash
ruby splitmerge_activity.rb
ruby splitmerge_workflow.rb
ruby splitmerge_workflow_starter.rb
```

**Comment by EronHennessey** [comment]
Fixed in the reference PR. Here's the [fixed README](https://github.com/awslabs/aws-flow-ruby-samples/blob/master/samples/split_merge/README.md)

**Comment by mojodna** [comment]
:+1:, thanks!

**Comment by EronHennessey** [comment]
Glad to be able to help, and thank you for noting the discrepancy in the first place! :)
